### PR TITLE
Build docker image on github actions and publish to github container registry

### LINKED ISSUE #4: Make available on Docker Hub
Make the docker image available on the official Docker registry, so that one doesn't need to clone/download the repo...

Btw, great initiative and I really appreciate your effort on doing Google's job providing an emulator.

### PR DESCRIPTION
**Pull request by acoulton**
Fixes #4 

This would be easier for you to set up if github packages would support properly public images, but unfortunately after getting that working I discovered they don't (all clients have to be authenticated even if the package is public, it turns out).

Apologies in advance if you already know all the next steps.

Therefore I've configured this to push to docker hub instead. This needs a very brief bit of setup from you:

* Create an account at https://hub.docker.com/ if you don't have one, ideally called `aertje` to match your github user
* Create a new public docker repository at https://hub.docker.com/repository/create - it should be named aertje/cloud-tasks-emulator to match this repo
* Create a new docker access token at https://hub.docker.com/settings/security
* In your github settings for this repo at https://github.com/aertje/cloud-tasks-emulator/settings/secrets create two secrets: `DOCKER_PUSH_TOKEN` is the token you just created on docker. `DOCKER_PUSH_USERNAME` is `aertje`

That should be all that's required for github actions to start building and publishing this. It builds on every push to your repo (not on pull requests, just the merge). The image is tagged with the branch name and the commit sha.

If you'd like to publish to a different docker user account / repository name you just need to change the `repository` argument at the end of the YAML.

It would obviously be great to also get the tests running on github actions but I don't know go enough to work out how to do that!

### CODE REVIEW

**Comment by aertje** [comment]
Thanks for making this so easy for me - will definitely look into this, probably on the weekend.

**Comment by aertje** [comment]
@acoulton sorry i haven't gotten to this yet - do really appreciate it though;
Would it make sense to move this instead to Github container registry now that that's available you reckon?

**Comment by acoulton** [comment]
No worries :) 

It would make a lot of sense to move it to Github container registry. Unfortunately (at least for the beta) it only supports authentication with a Personal Access Token. Currently if you create the token through the web UI, it quietly adds `repo` scope - which means the token has pretty much unlimited privileges to impersonate the creator across all organisations they belong to. If that token is made available to github actions it's a pretty major security issue (anyone with push access can gain access to the token and hijack your account).

I actually raised this with github end of last week and they're going to update the GHCR docs to highlight the security concerns. It also turns out the `repo` scope isn't actually required and they're planning to update the web-based "create a token" flow to stop it adding that scope.

It might be OK for this:

- If you're the only one with direct push access then the potential for leaking the token is very low (the secrets aren't available when building a pull request from a fork).

- If you create the token through the command line you can restrict it to just `packages:read` and `packages:write` so although that could still be misused the risks are significantly lower especially if you're not using github packages for anything else (and only as bad as having your docker token in here as per the original suggestion).

The actual flow for pushing to GHCR is pretty straightforward so I could update the workflow yaml for that easily enough. I can also provide instructions for creating the limited-privilege token through the command line.

If you're not comfortable giving it a personal access token of your own then I think we could also create a free github bot user account and give it write access to just this package, which would then be pretty secure.

**Comment by aertje** [comment]
Whoa, you really gave this a good amount of thought, and sounds like a valid concern you raise!

I am a bit confused though, are you suggesting **not** to use the automatically generated [GITHUB_TOKEN](https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow)? From what I can tell that token has permissions limited to the repo that contains the workflow and is only valid during the execution of the job, which seems secure to me?

**Comment by acoulton** [comment]
@aertje it was something we were already aware of - we'd been looking at moving some of our own projects to GHCR just after it came out - and I've been cautious for a very long time about the security implications of creating personal access tokens with `repo` scope. They're really a legacy permissions model and totally unsuited to modern github features / usage IMHO...

You're right that for most things on actions, `GITHUB_TOKEN` is the way to go - indeed github's security docs explicitly say [you should never use personal access tokens from your own account](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#considering-cross-repository-access).

Unfortunately for GHCR you *can't* use `GITHUB_TOKEN`. GHCR containers are a totally separate entity to repos (they live directly under an organisation / user). I guess this was the easiest way for them to make it so you can `Set fine-grained permissions and visibility independent of repository permissions and visibility`.

Therefore the `GITHUB_TOKEN` doesn't have / can't be granted permissions on a container - you [have to use a personal access token](https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images#authenticating-with-the-container-registry).

The best thing would probably be to create a free bot user that only has permission to push to this image. 

You'd need to set that up and give it the correct permissions etc, but I can update the actions code and write you a list of instructions?

**Comment by aertje** [comment]
Cheers @acoulton, appreciate the explanation. I'm ok to use a personal token as per your original suggestion for now then; looks like it will only need to be a temporary measure until they support a token (or equivalent) for ghcr. If you don't mind updating the code for that, please go ahead!

**Comment by acoulton** [comment]
@aertje I'm sorry this took so long to get back to. 

I've redone it to push to GHCR - because of github's security model the container will only be published on a `push` build - so if you or a collaborator pushes direct to this repo, or merges a PR. For an external pull request the job will build the container, to verify it's OK, then discard it.

Assuming you're still happy to use an access token for your own account, rather than setup a dedicated bot user, there's just two final things left that you'll need to do:

### Configure the package publishing secret (before merge)

* Go to https://github.com/settings/tokens/new
* tick `write:packages` scope
* **UNTICK** `repo` scope (which github will have automatically selected, but is not required and should not be granted as above)
* Generate the token and take a copy
* Go to https://github.com/aertje/cloud-tasks-emulator/settings/secrets/actions/new
* Create a secret called `GH_CR_IMG_PUSH_PAT` with your new access token as the value

### Make the image public (after merge)

Once the merge build completes, go to https://github.com/users/aertje/packages/container/cloud-tasks-emulator/settings and click `Make public` down at the bottom of the page (in the "Danger Zone").

**Comment by acoulton** [comment]
I've added a smoketest to verify that the container is built properly / the external networking interface works as expected. I've tried to structure and format the go properly but let me know if there are any issues.

**Comment by aertje** [comment]
Amazing work and very useful for me to learn how this is done! Thanks.

**Comment by acoulton** [comment]
You're welcome - very useful for me too :)

**Pull request merged**
