### PR TITLE
Add mutexes for maps

### PR DESCRIPTION
**Pull request by aertje**

### CODE REVIEW

**Comment by aertje** [comment]
@JimPatterson here's what I came up with - what do you reckon? I like it a bit better as it doesn't require the casts and seems a bit more DRY. Keen to know what you think.

**Comment by JimPatterson** [comment]
I will give it a look and test it in my dev environment sometime next week and get back to you.

**Review by phalimee — APPROVED** [review]

**Comment by aertje** [comment]
@JimPatterson Any luck? Still keen to hear whether you think this is a good alternative or not.

**Comment by JimPatterson** [comment]
@aertje I reviewed the code and it looks sounds.  I also ran some tests firing off lots of requests (~1000) at once and it worked great.

This approach is mush less invasive.  Great Work!

**Review by JimPatterson — APPROVED** [review]

**Comment by aertje** [comment]
Great, thanks @JimPatterson!

**Pull request merged**
