### PR TITLE
Implement support for sending OIDC auth tokens with request

### PR DESCRIPTION
**Pull request by acoulton**
> _Reproduced the new README section here for ease_

Adds support for [OIDC token](https://cloud.google.com/tasks/docs/creating-http-target-tasks#token) authentication for HTTP target tasks. Tokens will be issued and signed by the emulator's (insecure) private key. The emulator will accept, and issue tokens for, **any** ServiceAccountEmail provided by the client.

By default, the JWT `iss` (issuer) field is "http://cloud-tasks-emulator".

Optionally, the emulator can host an HTTP OIDC discovery endpoint. This allows your application to verify tokens at runtime with the full online flow. 

To enable this, specify an issuer value at startup:

```
go run ./ -openid-issuer http://localhost:8980
```

With this flag:

* JWTs will have an `iss` field of `http://localhost:8980`
* The [discovery document](https://developers.google.com/identity/protocols/oauth2/openid-connect#discovery) will be available at `http://localhost:8980/.well-known/openid-configuration`
* The emulator's public key(s) (in JWK format) will be available at `http://localhost:8980/jwks`

The `-openid-issuer` URL can be any `http://hostname:port` value that your application code can route to. The endpoint listens on `0.0.0.0` for easy use in docker / k8s environments.

You can, of course, export the content of the `/jwks` url if you prefer to hardcode the public keys in your application.

### CODE REVIEW

**Comment by aertje** [comment]
Thanks @acoulton ! I'm afraid I won't get to this until the weekend though!

**Comment by acoulton** [comment]
No problem

**Comment by aertje** [comment]
What a fantastic piece of work!

**Review by aertje — APPROVED** [review]

**Comment by acoulton** [comment]
> What a fantastic piece of work!

Thanks very much :) Did you mean to merge it?

**Comment by aertje** [comment]
Just waiting for a colleague (with more go experience) to have a look too.

**Comment by acoulton** [comment]
ah, no worries - thanks.

**Comment by acoulton** [comment]
Fab, thanks :)

**Pull request merged**
