### PR TITLE
Tasks v2

### PR DESCRIPTION
**Pull request by aertje**

### CODE REVIEW

**Comment by aertje** [comment]
@acoulton The tests (all two of them ;)) broke, so I had to fix them up. Wasn't sure how to add on top of your PR from a fork, so I just added this one.

**Comment by avandehulsbeek** [comment]
@acoulton are you happy with this?

**Comment by acoulton** [comment]
@aertje looks good to me thanks - sorry for the slow reply. How do you run the tests? I did have a (probably too quick) go at doing that at the time but I couldn't figure it out...

**Comment by aertje** [comment]
`go test` does the trick!

**Pull request merged**
